### ISSUE TITLE
Zoom to Feature is broken

### ISSUE THREAD

**Issue by acang-gs** [Geosyntec/StormPiper#263]
Likely by the zoom level setting done to conditionally render raster layers

**Comment by austinorr** [comment]
do we need to conditionally render the rasters? actually the minZoom and maxZoom props already handle that natively, without us tracking zoom state. 

I think the zoomLevel prop was only used to conditionally render the pipe and inlet vector layers, but that's not needed either.

I also noticed that users can't zoom or pan far away from Tacoma, but this limit is not required, nor does it fix a problem that a user has.

both functions are removed in #265, and users can now pan and zoom again however hey please. Additionally, there was no performance improvement to the conditional render, since all layers are loaded async on page load, so conditional vector renders were removed.

There were a couple significant optimizations to be had here though: 
1) only fetch the fields we need from the paginated calls. The original implementation pulled outfields=* which is significantly slower if the resource has lots of attributes.
2) made the layers aware of zorder so that the BMPs are always on top.
3) re-ordered the layer panel so that the base layers are at the bottom. primary data first, then supporting data, then the reference base layer underlay rasters.
