### ISSUE TITLE
Spruce up css

### ISSUE THREAD

**Issue by acang-gs** [Geosyntec/StormPiper#79]
A few components need to have their styles revised to match our Material UI style, and to look more polished overall. As of the v0.2.0 release, these include:

- The login and registration forms
- The layer component selector
- The BMP stat panel

I've taken some time to replace some of my initial form and panel features with their Material UI counterparts, which has gone a long way to improving their look and feel. For example, our panels now have nice bezeled corners and shadows, and our form inputs are more modern looking: 
<img width="1440" alt="Screen Shot 2022-09-13 at 4 21 52 PM" src="https://user-images.githubusercontent.com/74433074/190026329-fefd6b86-1ac3-4b81-a114-91467d306799.png">

@cnilsen @austinorr please feel free to drop some comments in here with suggestions on style upgrades, especially if you see any low hanging fruit items. If we have some larger tasks, like perhaps a revision of the layer selector, then we can extract that into a separate issue.

**Comment by austinorr** [comment]
@cnilsen @acang-gs closing due to the recent multi-week styling overhaul we recently undertook.
-[x] zero .css files
-[x] mui/material components (i.e., not the raw ones from mui/core
-[x] site wide theme and layout conventions
-[x] numerous component refactors to break large files down into discrete component parts.
